#
#   BSD 3-Clause License
#   Copyright (c) 2023, Doosan Robotics Inc.
#
# Add python def function with DRL foreach User Command
# Define Global Variable for User Commands
# Description: Add variable declaration code to the top of this DRL file in 'channel.receive("req_to_save_commands_def_as_sub_program..') in the UserCommandService.ts file.
# e.g. Global_ip = "192.168.1.1"
# e.g. Global_initPoseZyx = [0,0,0,0,0,0]
# You can use Global_ip and Global_initPoseZyx in anywhere using 'global {variablea_name}' syntex in custom function.
# User Command Sample1
def usercommand_sample_function(waitTime, useOverridePose, initPoseZyx):
    global Global_ip
    global Global_initPoseZyx
    # tp_popup(message='Connected to ' + Global_ip)
    wait(waitTime)
    # you can use move() command using posx() without orientation type(zyz, zyx and more)
    # programming manual: https://manual.doosanrobotics.com/en/programming/3.2.1/Publish/posx-x-0-y-0-z-0-a-0-b-0-c-0
    if useOverridePose:
        posx_with_ori_type = posx(initPoseZyx, ori_type=DR_ELR_ZYX)
    else:
        posx_with_ori_type = posx(Global_initPoseZyx, ori_type=DR_ELR_ZYX)

    movel(posx_with_ori_type)

def usercommand_sample_calcXyzToZyz(pos):
    # coordinate transformation Manually using rpy2eul()
    # programming manual: https://manual.doosanrobotics.com/en/programming/3.2.1/Publish/rpy2eul-yaw-pitch-roll
    newRotation = rpy2eul([pos[3],pos[4],pos[5]])
    newPos = [pos[0],pos[1],pos[2],newRotation[0],newRotation[1],newRotation[2]]
    tp_popup(message='pose convert from zyx to zyz\nzyx: ' + str(pos) + '\nzyz: '+ str(newPos))
    return newPos

